version: '3'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      MONGO_INITDB_DATABASE: triana-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: